site_name: Rick-VFS
site_description: Minio/S3 client VFS abstraction library
strict: true
site_url: https://github.com/oddbit-project/rick_vfs/
repo_name: oddbit-project/rick_vfs
repo_url: https://github.com/oddbit-project/rick_vfs/

theme:
  name: material

nav:
- Overview: index.md

plugins:
- search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
